[package]
name = "bank"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
env_logger = "0.9"
log = "0.4"
serde = { version = "1", features = ["derive"]}

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"
